// Generated by gencpp from file legged_wbc/nvector3f.msg
// DO NOT EDIT!


#ifndef LEGGED_WBC_MESSAGE_NVECTOR3F_H
#define LEGGED_WBC_MESSAGE_NVECTOR3F_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <legged_wbc/vector3f.h>

namespace legged_wbc
{
template <class ContainerAllocator>
struct nvector3f_
{
  typedef nvector3f_<ContainerAllocator> Type;

  nvector3f_()
    : data()  {
    }
  nvector3f_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::legged_wbc::vector3f_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::legged_wbc::vector3f_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::legged_wbc::nvector3f_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::legged_wbc::nvector3f_<ContainerAllocator> const> ConstPtr;

}; // struct nvector3f_

typedef ::legged_wbc::nvector3f_<std::allocator<void> > nvector3f;

typedef boost::shared_ptr< ::legged_wbc::nvector3f > nvector3fPtr;
typedef boost::shared_ptr< ::legged_wbc::nvector3f const> nvector3fConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::legged_wbc::nvector3f_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::legged_wbc::nvector3f_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::legged_wbc::nvector3f_<ContainerAllocator1> & lhs, const ::legged_wbc::nvector3f_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::legged_wbc::nvector3f_<ContainerAllocator1> & lhs, const ::legged_wbc::nvector3f_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace legged_wbc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::legged_wbc::nvector3f_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::legged_wbc::nvector3f_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_wbc::nvector3f_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_wbc::nvector3f_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_wbc::nvector3f_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_wbc::nvector3f_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::legged_wbc::nvector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "390cbff96d168abc35f84f5ed0728288";
  }

  static const char* value(const ::legged_wbc::nvector3f_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x390cbff96d168abcULL;
  static const uint64_t static_value2 = 0x35f84f5ed0728288ULL;
};

template<class ContainerAllocator>
struct DataType< ::legged_wbc::nvector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "legged_wbc/nvector3f";
  }

  static const char* value(const ::legged_wbc::nvector3f_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::legged_wbc::nvector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vector3f[] data\n"
"================================================================================\n"
"MSG: legged_wbc/vector3f\n"
"float64 x \n"
"float64 y \n"
"float64 z \n"
;
  }

  static const char* value(const ::legged_wbc::nvector3f_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::legged_wbc::nvector3f_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nvector3f_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::legged_wbc::nvector3f_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::legged_wbc::nvector3f_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::legged_wbc::vector3f_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEGGED_WBC_MESSAGE_NVECTOR3F_H
