// Generated by gencpp from file legged_wbc/vector3f.msg
// DO NOT EDIT!


#ifndef LEGGED_WBC_MESSAGE_VECTOR3F_H
#define LEGGED_WBC_MESSAGE_VECTOR3F_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace legged_wbc
{
template <class ContainerAllocator>
struct vector3f_
{
  typedef vector3f_<ContainerAllocator> Type;

  vector3f_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  vector3f_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::legged_wbc::vector3f_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::legged_wbc::vector3f_<ContainerAllocator> const> ConstPtr;

}; // struct vector3f_

typedef ::legged_wbc::vector3f_<std::allocator<void> > vector3f;

typedef boost::shared_ptr< ::legged_wbc::vector3f > vector3fPtr;
typedef boost::shared_ptr< ::legged_wbc::vector3f const> vector3fConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::legged_wbc::vector3f_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::legged_wbc::vector3f_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::legged_wbc::vector3f_<ContainerAllocator1> & lhs, const ::legged_wbc::vector3f_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::legged_wbc::vector3f_<ContainerAllocator1> & lhs, const ::legged_wbc::vector3f_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace legged_wbc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::legged_wbc::vector3f_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::legged_wbc::vector3f_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_wbc::vector3f_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::legged_wbc::vector3f_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_wbc::vector3f_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::legged_wbc::vector3f_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::legged_wbc::vector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::legged_wbc::vector3f_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::legged_wbc::vector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "legged_wbc/vector3f";
  }

  static const char* value(const ::legged_wbc::vector3f_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::legged_wbc::vector3f_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x \n"
"float64 y \n"
"float64 z \n"
;
  }

  static const char* value(const ::legged_wbc::vector3f_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::legged_wbc::vector3f_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vector3f_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::legged_wbc::vector3f_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::legged_wbc::vector3f_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEGGED_WBC_MESSAGE_VECTOR3F_H
